name: PR Build Check

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-check:
    name: Verify Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'